In [1]:
#imbalance
#normalize to 0-1
#out: M,N,D
#some data doesn't exist in B,C and CD-CI, also CV,CW exclude those null instances

import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score, nan_euclidean_distances
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.optimizers import SGD


pd.set_option('display.max_rows', 200)

In [2]:
#create DataFrame
velux_dataset_original = pd.read_csv("sample_data_velux.csv", sep=';', usecols=['if_returning_customer','space_type','project_type','avg_time_per_session_sec','number_of_page_views','duration_of_pages_kidsroom_sec','duration_of_pages_homeoffice_sec','duration_of_pages_livingroom_sec','duration_of_pages_hallwaycorridor_sec','duration_of_pages_kitchen_sec','duration_of_pages_bathroom_sec','duration_of_pages_bedroom_sec','duration_of_pages_extension_sec','duration_of_pages_loftconversion_sec','duration_of_pages_renovation_sec','duration_of_pages_newbuild_sec','duration_of_pages_upgrading_sec','duration_of_pages_reroofing_sec','duration_of_pages_replacement_sec','duration_of_pages_flatroof_sec'])
# 'number_of_pages_allspaces','number_of_pages_kidsroom','number_of_pages_homeoffice','number_of_pages_livingroom','number_of_pages_hallwaycorridor','number_of_pages_kitchen','number_of_pages_bathroom','number_of_pages_bedroom','number_of_pages_extension','number_of_pages_loftconversion','number_of_pages_renovation','number_of_pages_newbuild','number_of_pages_upgrading','number_of_pages_reroofing','number_of_pages_replacement','number_of_pages_flatroof',

In [3]:
#check data type
velux_dataset_original.dtypes

project_type                             object
space_type                               object
if_returning_customer                     int64
avg_time_per_session_sec                  int64
number_of_page_views                      int64
duration_of_pages_kidsroom_sec            int64
duration_of_pages_homeoffice_sec          int64
duration_of_pages_livingroom_sec          int64
duration_of_pages_hallwaycorridor_sec     int64
duration_of_pages_kitchen_sec             int64
duration_of_pages_bathroom_sec            int64
duration_of_pages_bedroom_sec             int64
duration_of_pages_extension_sec           int64
duration_of_pages_loftconversion_sec      int64
duration_of_pages_renovation_sec          int64
duration_of_pages_newbuild_sec            int64
duration_of_pages_upgrading_sec           int64
duration_of_pages_reroofing_sec           int64
duration_of_pages_replacement_sec         int64
duration_of_pages_flatroof_sec            int64
dtype: object

In [4]:
#inspect data
cols = list(velux_dataset_original)
toDelete = []
toObject = []

for col in cols:
    if len(velux_dataset_original[col].unique()) == 1 or (len(velux_dataset_original[col].unique()) == 2 and np.NaN in velux_dataset_original[col].unique()):
         toDelete.append(col)
    elif col[0:2] == 'if':
        toObject.append(col)    

print(toDelete)

[]

In [5]:
#clean the data

#drop cols with only one uniqe value
velux_dataset_original.drop(toDelete, axis='columns',inplace=True)
velux_dataset = velux_dataset_original.copy()
#drop cols with too little data
# velux_dataset = velux_dataset_original.drop(['final_id','first_brproject','first_brspace','marketing_consent_optout_date'], axis='columns')

#convert type of data from int64 to Object where apropriate
for col in toObject:
    velux_dataset[col] = velux_dataset[col].astype(str)

In [6]:
# #create small dataset by deleting all rows with any NaN values
# velux_dataset_small = velux_dataset.dropna()

# #create dataset with synthesied missing values
# velux_dataset_synthesised= [] #TODO

#create big dataset by deleting cols with too many missing data
# velux_dataset_big = velux_dataset.drop(['most_frequent_page_project_type','most_frequent_page_space_type','second_frequent_page_project_type','second_frequent_page_space_type','third_frequent_page_project_type','third_frequent_page_space_type'], axis='columns')
velux_dataset_big = velux_dataset.copy()

In [7]:
velux_dataset_big

,project_type,space_type,if_returning_customer,avg_time_per_session_sec,number_of_page_views,duration_of_pages_kidsroom_sec,duration_of_pages_homeoffice_sec,duration_of_pages_livingroom_sec,duration_of_pages_hallwaycorridor_sec,duration_of_pages_kitchen_sec,duration_of_pages_bathroom_sec,duration_of_pages_bedroom_sec,duration_of_pages_extension_sec,duration_of_pages_loftconversion_sec,duration_of_pages_renovation_sec,duration_of_pages_newbuild_sec,duration_of_pages_upgrading_sec,duration_of_pages_reroofing_sec,duration_of_pages_replacement_sec,duration_of_pages_flatroof_sec
0,replacement,livingroom,1,375,86,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,replacement,bedroom,1,50,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,loftconversion,bedroom,1,3754,144,0,0,0,0,0,0,1122,0,0,6588,0,42,0,22,31981
3,loftconversion,no_space_intent,1,1433,57,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,loftconversion,no_space_intent,1,620,15,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4369,replacement,bedroom,0,167,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4370,replacement,bathroom,0,230,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,153
4371,replacement,bedroom,0,192,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4372,replacement,bathroom,1,206,6,0,0,0,0,0,0,0,0,0,30,0,128,0,0,0
4373,replacement,bathroom,0,239,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [8]:
#once again clean cols with only one value
toDeleteBig = []

for col in velux_dataset_big:
    if len(velux_dataset_big[col].unique()) == 1 or (len(velux_dataset_big[col].unique()) == 2 and np.NaN in velux_dataset_big[col].unique()):
        toDeleteBig.append(col)

velux_dataset_big.drop(toDeleteBig,axis='columns',inplace=True)

In [9]:
#check for class imbalance (could use Tomek Links, SMOTE, Metric like F1, and Random Forest algorithm, since tree based algos work well with imbalanced data)
for col in velux_dataset_big:
    print(velux_dataset_big[col].value_counts(), '\n')

project_type
replacement       2720
loftconversion     884
upgrading          427
renovation         180
newbuild           163
Name: count, dtype: int64

space_type
bedroom                1487
corridororstaircase     605
bathroom                553
livingroom              528
allspaces               437
no_space_intent         283
kitchen                 193
kidsroom                190
office                   98
Name: count, dtype: int64

if_returning_customer
0    2642
1    1732
Name: count, dtype: int64

avg_time_per_session_sec
30       33
150      27
90       22
103      21
92       20
         ..
6500      1
13173     1
6145      1
1598      1
507       1
Name: count, Length: 1244, dtype: int64

number_of_page_views
2      1005
3       748
4       513
5       369
6       273
7       220
8       148
9       141
10      122
11       93
13       87
12       75
14       64
15       63
16       51
19       37
20       33
17       31
18       28
21       22
23       21
27       19
22       17
24       14
25       14
26       13
29       12
28       11
30        9
35        8
31        7
32        7
38        6
33        6
34        6
37        5
40        5
41        5
44        4
46        4
45        4
54        3
36        3
39        3
49        2
66        2
58        2
60        2
48        2
92        2
93        2
43        2
482       1
55        1
72        1
65        1
61        1
96        1
53        1
75        1
71        1
99        1
47        1
77        1
52        1
73        1
86        1
167       1
76        1
62        1
256       1
56        1
333       1
68        1
297       1
522       1
153       1
163       1
57        1
144       1
74        1
Name: count, dtype: int64

duration_of_pages_kidsroom_sec
0       4331
14         2
30         2
15         2
9          2
22         2
48         2
5          2
100        2
33         1
93         1
39         1
70         1
45         1
244        1
34         1
66         1
55         1
168        1
20         1
127        1
134        1
137        1
2369       1
49         1
4          1
60         1
32         1
2          1
40         1
12         1
76         1
43         1
10         1
114        1
90         1
Name: count, dtype: int64

duration_of_pages_homeoffice_sec
0        4301
30          3
17          3
31          2
29          2
25          2
9           2
21          2
46          2
164         1
251         1
569         1
255         1
43          1
79          1
150         1
232         1
50          1
64          1
95          1
630         1
37          1
221         1
4           1
209         1
75          1
236         1
54          1
49          1
92          1
13          1
27          1
32          1
56          1
94          1
88          1
58          1
8179        1
1190        1
14          1
1887        1
134         1
360         1
63          1
7           1
36          1
196         1
113         1
44          1
226         1
353         1
120         1
86          1
795         1
16          1
269         1
2           1
11          1
48          1
111         1
59          1
17127       1
12          1
57          1
Name: count, dtype: int64

duration_of_pages_livingroom_sec
0        4297
29          5
39          4
13          3
21          2
42          2
7           2
133         2
43          2
1           2
9           2
27          2
32          2
15          2
59          1
69          1
62          1
3           1
301         1
729         1
44          1
107         1
36          1
798         1
117         1
76          1
175         1
19          1
8           1
208         1
2           1
20          1
380         1
244         1
84          1
23          1
6           1
34          1
22          1
16          1
377         1
870         1
4           1
520         1
177         1
48          1
112         1
46          1
237         1
32395       1
170         1
31          1
35          1
77          1
17          1
176         1
30          1
811         1
751         1
Name: count, dtype: int64

duration_of_pages_hallwaycorridor_sec
0        4142
30          7
22          4
21          4
44          4
13          4
16          4
159         3
65          3
64          3
88          3
43          3
60          2
67          2
9           2
5           2
4           2
677         2
18          2
196         2
2           2
28          2
225         2
17          2
3           2
27          2
87          2
7           2
201         2
11          2
59          2
24          2
8           2
46          2
2229        1
882         1
312         1
89          1
94          1
228         1
348         1
338         1
554         1
47          1
346         1
303         1
155         1
591         1
439         1
56          1
48          1
100         1
66          1
889         1
1841        1
11450       1
1272        1
281         1
471         1
1984        1
542         1
279         1
1583        1
341         1
400         1
132         1
1446        1
1417        1
797         1
301         1
55          1
192         1
5669        1
15          1
200         1
164         1
10787       1
37          1
748         1
388         1
141         1
108         1
71          1
776         1
90          1
985         1
207         1
1107        1
1154        1
549         1
1275        1
147         1
384         1
1611        1
190         1
152         1
259         1
796         1
432         1
1219        1
465         1
530         1
34          1
765         1
396         1
1168        1
448         1
761         1
35          1
186         1
3300        1
5160        1
102         1
161         1
641         1
41          1
557         1
23          1
122         1
260         1
310         1
1565        1
187         1
1           1
582         1
722         1
571         1
8432        1
199         1
242         1
874         1
326         1
173         1
283         1
5515        1
6           1
29          1
49          1
934         1
78          1
3948        1
406         1
817         1
562         1
68          1
256         1
170         1
680         1
12          1
76          1
1140        1
33          1
682         1
714         1
689         1
92          1
1302        1
109         1
85          1
243         1
210         1
93          1
129         1
38          1
150         1
937         1
39          1
101         1
355         1
212         1
144         1
1856        1
294         1
251         1
356         1
8896        1
430         1
82          1
620         1
293         1
Name: count, dtype: int64

duration_of_pages_kitchen_sec
0        4333
36          3
18          1
33          1
234         1
353         1
388         1
242         1
35          1
352         1
66          1
24          1
12          1
39          1
142         1
125         1
728         1
188         1
63          1
373         1
154         1
11          1
55          1
9690        1
2           1
525         1
181         1
43          1
61          1
19          1
68          1
40          1
28          1
199         1
187         1
30          1
11957       1
38          1
50          1
7           1
Name: count, dtype: int64

duration_of_pages_bathroom_sec
0        4292
29          3
96          2
118         2
23          2
28          2
42          2
64          2
2           2
110         2
81          2
25          1
56          1
413         1
95          1
92          1
1           1
61          1
90          1
112         1
30          1
40          1
417         1
161         1
19          1
319         1
63          1
176         1
10          1
7           1
13          1
75          1
109         1
87          1
58          1
271         1
77          1
108         1
106         1
197         1
98          1
207         1
45          1
33294       1
104         1
127         1
199         1
650         1
72          1
39          1
103         1
14          1
74          1
89          1
49          1
88          1
12          1
167         1
1084        1
235         1
85          1
2715        1
41          1
21          1
66          1
123         1
68          1
32          1
50          1
27          1
270         1
57          1
Name: count, dtype: int64

duration_of_pages_bedroom_sec
0       4166
30         6
15         5
18         5
29         4
23         4
24         4
58         4
1          3
22         3
42         3
12         3
11         3
38         3
80         3
17         3
36         3
33         3
34         3
78         3
16         3
89         2
61         2
107        2
52         2
50         2
72         2
10         2
46         2
49         2
14         2
106        2
13         2
87         2
9          2
109        2
96         2
25         2
68         2
19         2
101        2
37         2
63         2
100        2
3          2
924        1
71         1
2163       1
74         1
99         1
132        1
589        1
152        1
173        1
27         1
213        1
149        1
4908       1
122        1
32         1
537        1
194        1
54         1
531        1
8          1
357        1
20         1
273        1
98         1
117        1
79         1
450        1
35         1
793        1
360        1
28         1
51         1
65         1
227        1
4124       1
1663       1
231        1
655        1
253        1
256        1
43         1
843        1
243        1
4672       1
207        1
95         1
342        1
2187       1
47         1
45         1
31         1
135        1
212        1
55         1
75         1
73         1
48         1
182        1
6          1
228        1
1986       1
59         1
2033       1
120        1
226        1
251        1
44         1
1122       1
465        1
85         1
90         1
86         1
5          1
40         1
66         1
26         1
62         1
150        1
76         1
809        1
94         1
69         1
7431       1
103        1
21         1
102        1
1110       1
39         1
82         1
Name: count, dtype: int64

duration_of_pages_extension_sec
0      4370
290       1
228       1
31        1
117       1
Name: count, dtype: int64

duration_of_pages_loftconversion_sec
0        4305
30          4
91          4
60          2
34          2
221         1
149         1
721         1
216         1
175         1
40          1
148         1
211         1
41          1
291         1
1591        1
219         1
19          1
135         1
44          1
163         1
100         1
122         1
78          1
58          1
47          1
1283        1
45          1
7           1
184         1
124         1
118         1
43          1
9           1
10          1
150         1
197         1
418         1
15          1
59          1
32          1
3           1
235         1
51          1
26          1
401         1
162         1
752         1
66084       1
613         1
55          1
35          1
340         1
310         1
276         1
205         1
33          1
477         1
79          1
99          1
137         1
16          1
Name: count, dtype: int64

duration_of_pages_renovation_sec
0        4269
30          7
42          2
90          2
164         2
13          2
101         2
21          2
41          2
19          2
271         2
151         2
73          2
7           2
126         2
39          2
165         1
125         1
46          1
8           1
962         1
43          1
798         1
2388        1
61          1
2080        1
36          1
229         1
81          1
32          1
57          1
52          1
458         1
1168        1
182         1
47          1
49          1
208         1
31          1
844         1
185         1
143         1
116         1
23          1
310         1
339         1
780         1
55          1
102         1
914         1
342         1
1173        1
907         1
26          1
621         1
2363        1
169         1
133         1
16          1
15          1
2356        1
346         1
80          1
91          1
2815        1
37262       1
424         1
162         1
18          1
150         1
255         1
2           1
931         1
4           1
6588        1
35          1
51          1
176         1
22          1
9           1
44          1
14056       1
72          1
170         1
775         1
1634        1
Name: count, dtype: int64

duration_of_pages_newbuild_sec
0        4360
17106       1
14          1
199         1
140         1
50          1
17          1
373         1
10          1
33          1
188         1
66          1
691         1
76          1
728         1
Name: count, dtype: int64

duration_of_pages_upgrading_sec
0        4316
30          5
32          2
42          2
38          2
62          2
20          2
6           1
110         1
58          1
57          1
630         1
161         1
85          1
321         1
391         1
2496        1
167         1
12          1
29          1
99          1
37          1
44          1
91          1
160         1
24          1
16          1
65          1
19          1
83          1
49          1
10860       1
72          1
861         1
116         1
50          1
21          1
28          1
26          1
1591        1
145         1
90          1
23          1
33          1
55          1
53          1
63          1
61          1
10          1
128         1
Name: count, dtype: int64

duration_of_pages_reroofing_sec
0      4362
26        3
714       1
813       1
114       1
44        1
125       1
14        1
62        1
36        1
37        1
Name: count, dtype: int64

duration_of_pages_replacement_sec
0        4245
30         17
21          3
13          3
34          3
74          2
55          2
11          2
128         2
202         2
118         2
73          2
25          2
217         2
96          2
51          2
84          2
36          1
152         1
1014        1
184         1
35          1
77          1
188         1
12          1
561         1
287         1
240         1
254         1
94          1
8019        1
316         1
68          1
562         1
229         1
50          1
293         1
298         1
116         1
259         1
83          1
18          1
1985        1
59          1
161         1
9           1
281         1
43          1
14182       1
523         1
548         1
141         1
805         1
6           1
62          1
400         1
162         1
60          1
204         1
67          1
69          1
258         1
85          1
9666        1
70          1
467         1
331         1
110         1
127         1
306         1
168         1
45          1
97          1
90          1
20          1
91          1
147         1
14          1
61          1
41          1
101         1
49          1
63          1
346         1
22          1
215         1
44          1
76          1
19          1
10          1
52          1
280         1
5           1
71          1
29          1
308         1
Name: count, dtype: int64

duration_of_pages_flatroof_sec
0        4100
4           7
30          6
35          6
5           5
9           5
22          5
18          5
6           5
33          5
34          5
41          4
15          4
90          4
52          4
12          4
27          4
24          3
14          3
13          3
45          3
46          3
39          3
17          3
21          3
16          3
26          3
20          3
10          3
37          3
29          3
50          2
3           2
126         2
176         2
32          2
53          2
38          2
255         2
172         2
294         2
79          2
180         2
25          2
140         2
194         2
28          2
76          2
8           2
7           2
31          2
42          2
51          2
66          2
115         2
65          2
1146        1
65260       1
2417        1
374         1
531         1
11          1
156         1
616         1
630         1
791         1
518         1
514         1
393         1
925         1
77          1
309         1
483         1
70          1
101         1
59          1
216         1
75          1
177         1
410         1
231         1
134         1
265         1
361         1
223         1
785         1
605         1
109         1
371         1
425         1
649         1
108         1
99          1
157         1
119         1
1009        1
277         1
135         1
834         1
383         1
1523        1
23          1
133         1
19          1
583         1
68          1
489         1
49          1
87          1
408         1
61          1
211         1
36          1
222         1
121         1
191         1
395         1
188         1
1004        1
130         1
195         1
204         1
78          1
162         1
253         1
420         1
1598        1
390         1
8814        1
272         1
47          1
354         1
375         1
282         1
44          1
950         1
110         1
283         1
190         1
447         1
324         1
444         1
138         1
3736        1
111         1
298         1
89          1
54          1
9427        1
1           1
81          1
1323        1
31981       1
439         1
2960        1
270         1
212         1
1031        1
106         1
153         1
Name: count, dtype: int64

In [10]:
#normalize data
velux_dataset_big_normalized = velux_dataset_big.copy()

for col in velux_dataset_big:
    if velux_dataset_big[col].dtype == 'int64':
        x = velux_dataset_big[col].values
        normalized=(x-x.min())/(x.max()-x.min())
        velux_dataset_big_normalized[col] = normalized

In [11]:
velux_dataset_big['project_type'].unique()

def integerEncoding(x):
    if x == 'replacement':
        return 1
    elif x == 'loftconversion':
        return 2
    elif x == 'upgrading':
        return 3
    elif x == 'newbuild':
        return 4
    elif x == 'renovation':
        return 5

In [12]:
#train classifier and check performance

y = velux_dataset_big['project_type'].apply(integerEncoding)
X = pd.get_dummies(velux_dataset_big.drop('project_type', axis='columns'))
X=X*1.00 #bool --> float64
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=56) # make a train-test split to train the model properly

knn = RandomForestClassifier() # create a classifier
model = knn.fit(X_train, y_train) # train the classifier
pred = knn.predict(X_test) # test the classifier
print(confusion_matrix(y_test, pred)) # print out a confusion matrix, classification report and accuracy score to check how did the algorithm do.
print(classification_report(y_test, pred))
print(accuracy_score(y_test, pred))

[[605 113  57  22  21]
 [186  49  14  11  10]
 [ 92  20  10   3   3]
 [ 27   9   3   2   3]
 [ 16  20   3   3  11]]
              precision    recall  f1-score   support

           1       0.65      0.74      0.69       818
           2       0.23      0.18      0.20       270
           3       0.11      0.08      0.09       128
           4       0.05      0.05      0.05        44
           5       0.23      0.21      0.22        53

    accuracy                           0.52      1313
   macro avg       0.26      0.25      0.25      1313
weighted avg       0.48      0.52      0.49      1313

0.5156130997715156